- package.json
- yarn.lock
Upgrade parcel to fix vulnerability.
> **Fix:** parcel vulnerability

- package.json
- src/Chart/legend/legend.ts
- src/Chart/series/renderers/text.ts
- src/PieChart/legend.ts
- src/ProcessFlow/renderers/links.ts
- src/utils/color.ts
- website/Marathon/index.ts
- website/MarathonRenderer.tsx
- Updated versions of d3 and @operational/components dependencies (and fixed marathon runner to account for changes to @operational/components).
- Fixed type errors that were causing `npm run build` to fail.
- Fixed logic error in process flows that was causing errors in certain cases.
> Fix visualizations website.

- src/ProcessFlow/README.md
Closed a code section correctly. Saving triggered the linter which made the other changes.
> Fix markdown.

- src/Grid/Grid.tsx
- src/Grid/axes/AxisBlock.tsx
- src/Grid/cells/CellBlock.tsx
- src/Grid/cells/GridCell.tsx
- src/Grid/column_headers/ColumnHeader.tsx
- src/Grid/column_headers/ColumnHeaderBlock.tsx
- src/Grid/column_headers/ColumnLabel.tsx
- src/Grid/gridConfig.ts
- src/Grid/gridConfigToAccessors.ts
- src/Grid/row_headers/RowHeader.tsx
- src/Grid/row_headers/RowHeaderBlock.tsx
- src/Grid/row_headers/RowLabel.tsx
- src/Grid/styles.ts
- src/Grid/types.ts
- src/Grid/utils.ts
- src/data_handling/__tests__/multidimensional_dataset.test.ts
- src/data_handling/multidimensional_dataset.ts
- src/index.ts
- src/utils/helpers.ts
> Grid component

- netlify.toml
- package.json
- src/website/Marathon/index.ts
- src/website/TestCases/index.ts
- src/website/TestCases/utils.ts
- src/website/VisualTests.tsx
- src/website/index.tsx
- yarn.lock
Fix errors in test runner. Now it runs through all examples without errors
> Fix some error in test runner

- src/website/TestCases/Grid/index.ts
- src/website/TestCases/Grid/table-1.tsx
- src/website/TestCases/Grid/table-2.tsx
- src/website/TestCases/Grid/table-3.tsx
- src/website/TestCases/index.ts
Add Grid examples to Marathon test runner (which is also serve as showcase of all components)
> Grid examples

- src/DataFrame/PivotFrame.ts
- src/DataFrame/PivotFramePreindexed.ts
- src/index.ts
Published as `@operational/visualizations@6.1.0-26d4512`
> Add PivotFramePreindexed

- src/DataFrame/PivotFrame.ts
- src/NewGrid/PivotGrid.tsx
- src/NewGrid/coordinateUtils.ts
- src/NewGrid/types.ts
- src/website/TestCases/Grid/table-1.tsx
- src/website/TestCases/Grid/table-3.tsx
- src/website/TestCases/Grid/table-5.tsx
- src/website/TestCases/Grid/table-6.tsx
Implemented additional headers
> Add headers for headers

- src/NewGrid/PivotGrid.tsx
- src/NewGrid/TableGrid.tsx
> Bold dimension names by default and tooltips for cut text

- src/website/TestCases/Grid/index.ts
- src/website/TestCases/Grid/table-7.tsx
> Demo of the bug with wrong grouping

- src/NewGrid/PivotGrid.tsx
- src/website/TestCases/Grid/table-1.tsx
As well added React.memo. Removed `"-"` as placeholder, because it is very noisy
> Add ability to change background of headers

- package.json
- src/Chart/README.md
- src/DataFrame/FragmentFrame.ts
- src/DataFrame/PivotFrame.ts
- src/DataFrame/stats.ts
- src/NewGrid/Axes.md
- src/NewGrid/PivotGrid.tsx
- src/NewGrid/coordinateUtils.ts
- src/NewGrid/types.ts
- src/website/TestCases/Grid/index.ts
- src/website/TestCases/Grid/table-2.tsx
This is just example of how it would be possible to integrate visualisations inside of the PivotGrid. It is full of magic numbers and `as any`. A lot of work to be done.
> Visualizations in new Grid

- netlify.toml
- package.json
- packages/frame/package.json
- packages/grid/package.json
- packages/visualizations-stories/.storybook/addons.js
- packages/visualizations-stories/.storybook/config.js
- packages/visualizations-stories/.storybook/preview-head.html
- packages/visualizations-stories/.storybook/tsconfig.json
- packages/visualizations-stories/.storybook/webpack.config.js
- packages/visualizations-stories/README.md
- packages/visualizations-stories/package.json
- packages/visualizations-stories/src/grid/1-basic-usage.stories.tsx
- packages/visualizations-stories/src/grid/1-pivot-grid.stories.tsx
- packages/visualizations-stories/src/grid/2-table-grid.stories.tsx
- packages/visualizations-stories/src/vizualisations/1-bar-chart.stories.tsx
- packages/visualizations-stories/tsconfig.json
- packages/visualizations/package.json
- yarn.lock
> Add storybook

- .eslintrc.json
- .travis.yml
- package.json
- packages/grid/src/PivotGrid.tsx
- packages/visualizations-stories/src/grid/1-pivot-grid.stories.tsx
- yarn.lock
Add 
- eslint
- lint-staged and prettier
> Improve dx

- package.json
- packages/frame/package.json
- packages/grid/package.json
- packages/visualizations/package.json
Fixes https://github.com/contiamo/operational-visualizations/issues/67
> Fix storybook reload bug

- packages/visualizations-stories/src/vizualisations/1-bar-chart.stories.tsx
- packages/visualizations-stories/src/vizualisations/2-bar-chart.stories.tsx
- packages/visualizations/Readme.md
- packages/visualizations/package.json
- packages/visualizations/src/Axis.tsx
- packages/visualizations/src/Bars.tsx
- packages/visualizations/src/Chart.tsx
- packages/visualizations/src/scale.ts
Improvements / fixes to the `Chart`, `Bars` and `Axis` component.
- Fix vertical axis directions (currently 0 is at the top of the y axis)
- User-defined margins for all sides independently rather than just one constant for all (allow a single number or an array to be provided)
- Add top and right axes
- Rename some of the props
- Move calls to `data.getCursor` to inside the `Bars` component. The user should not need to do this themselves.
https://contiamo.atlassian.net/secure/RapidBoard.jspa?rapidView=12&projectKey=EX&modal=detail&selectedIssue=EX-81
> Update bars and axes.

- packages/frame/src/DataFrame.ts
- packages/frame/src/PivotFrame.ts
- packages/grid/src/PivotGrid.tsx
- packages/grid/src/coordinateUtils.ts
- packages/visualizations-stories/src/grid/1-pivot-grid.stories.tsx
Change logic of PivotGrid and DataFrame to allow zero rows and columns
> Allow zero rows and columns in pivotgrid

- .adr.json
- docs/adr/0001-about-cursors.md
- docs/adr/README.md
- package.json
- yarn.lock
[ADR](https://github.com/joelparkerhenderson/architecture_decision_record) about cursor.
> Add ADR about cursor

- packages/grid/src/coordinateUtils.ts
- packages/visualizations-stories/src/grid/1-pivot-grid.stories.tsx
> Fix bug with pivoting in one direction

- packages/visualizations-stories/src/vizualisations/3-area-chart.stories.tsx
- packages/visualizations-stories/src/vizualisations/4-mixed-chart.stories.tsx
- packages/visualizations/package.json
- packages/visualizations/src/Area.tsx
- packages/visualizations/src/index.ts
Add basic area chart to library.
> Add area chart.

- packages/frame/src/DataFrame.ts
- packages/frame/src/FragmentFrame.ts
- packages/frame/src/PivotFrame.ts
- packages/frame/src/PivotFramePreindexed.ts
- packages/frame/src/secret.ts
- packages/frame/src/stats.ts
- packages/frame/src/types.ts
- Added `getCursor` to every frame
- Switched from raw data/schema to DataFrame as source
- added `unpivot` method
- added `isColumnCursor` utility
> Add getCursor everywhere

- docs/adr/0001-about-cursors.md
- packages/frame/src/DataFrame.ts
- packages/frame/src/FragmentFrame.ts
- packages/frame/src/stats.ts
- packages/frame/src/types.ts
- packages/visualizations/src/scale.ts
- packages/visualizations/src/types.ts
> Fix iteratable frame typo.

- packages/frame/src/utils.ts
Was returning false if the cursor index is 0.
> Fix isCursor util method.

- packages/visualizations/src/types.ts
> Fix AxialChart type.

- packages/frame/package.json
- packages/frame/src/PivotFrame.ts
- yarn.lock
Need this one first https://github.com/lukeed/flru/pull/7.
Use flru for cache as discussed previously
> Use flru for cache inside PivotFrame

- docs/adr/0002-about-render-props.md
- docs/adr/README.md
Question about render-prop. Open for comments. See file changes for details
> Add notes about render prop

- docs/adr/0003-about-caching.md
- docs/adr/README.md
Some ideas and explanation about caching strategies. See markdown file
> About caching

- docs/adr/0001-about-cursors.md
- docs/adr/0004-about-row-cursor.md
- docs/adr/README.md
- packages/frame/src/DataFrame.ts
- packages/frame/src/FragmentFrame.ts
- packages/frame/src/types.ts
- packages/grid/src/TableGrid.tsx
- packages/visualizations-stories/src/grid/1-pivot-grid.stories.tsx
- packages/visualizations/src/types.ts
See docs/adr/0004-about-row-cursor.md  for explanation
> Renamed RawRow to RowCursor

- packages/visualizations-stories/src/vizualisations/3-area-chart.stories.tsx
- packages/visualizations/src/Area.tsx
- packages/visualizations/src/types.ts
Stacked area charts that make use of new `GroupedFrame`.
https://contiamo.atlassian.net/secure/RapidBoard.jspa?rapidView=12&projectKey=EX&modal=detail&selectedIssue=EX-97
> Stacked areas.

- packages/grid/src/PivotGrid.tsx
- packages/grid/src/__tests__/coordinateUtils.test.ts
- packages/grid/src/coordinateUtils.ts
- packages/grid/src/types.ts
- packages/visualizations-stories/src/grid/1-pivot-grid.stories.tsx
Fixes https://github.com/contiamo/operational-visualizations/issues/74. This is a breaking change
> Flip row and column behaviour for measuresPlacement param

- packages/grid/src/PivotGrid.tsx
- packages/grid/src/__tests__/coordinateUtils.test.ts
- packages/grid/src/coordinateUtils.ts
- packages/grid/src/types.ts
- packages/visualizations-stories/src/grid/1-pivot-grid.stories.tsx
Reverts contiamo/operational-visualizations#116
> Revert "Flip row and column behaviour for measuresPlacement param"

- packages/visualizations-stories/src/vizualisations/1-bar-chart.stories.tsx
- packages/visualizations-stories/src/vizualisations/2-line-chart.stories.tsx
- packages/visualizations-stories/src/vizualisations/3-area-chart.stories.tsx
- packages/visualizations-stories/src/vizualisations/5-scatter-plot.stories.tsx
- packages/visualizations/src/Area.tsx
- packages/visualizations/src/Legend.tsx
- packages/visualizations/src/Line.tsx
- packages/visualizations/src/colors.ts
- packages/visualizations/src/index.ts
- packages/visualizations/src/theme.ts
- packages/visualizations/src/utils.ts
Simple legend component, using the same design as in the legacy library. 
https://contiamo.atlassian.net/secure/RapidBoard.jspa?rapidView=12&projectKey=EX&modal=detail&selectedIssue=EX-78
> Add legend component.

- packages/visualizations-stories/src/vizualisations/1-bar-chart.stories.tsx
- packages/visualizations-stories/src/vizualisations/6-pie-chart.stories.tsx
- packages/visualizations/src/PieChart.tsx
- packages/visualizations/src/index.ts
Basic pie chart component. 
https://contiamo.atlassian.net/secure/RapidBoard.jspa?rapidView=12&projectKey=EX&modal=detail&selectedIssue=EX-101
> Pie chart.

- packages/visualizations-stories/src/vizualisations/2-line-chart.stories.tsx
- packages/visualizations-stories/src/vizualisations/3-area-chart.stories.tsx
- packages/visualizations/src/Area.tsx
- packages/visualizations/src/Line.tsx
Do not interpolate across missing data for lines and areas. 
https://contiamo.atlassian.net/secure/RapidBoard.jspa?rapidView=12&projectKey=EX&modal=detail&selectedIssue=EX-90
#104
> Missing data in lines and areas.

- packages/frame/Readme.md
- packages/frame/package.json
- packages/grid/Readme.md
- packages/grid/package.json
- packages/visualizations/Readme.md
- packages/visualizations/package.json
Bump versions and add caution to the readme
> Bump versions

- packages/visualizations-stories/src/vizualisations/3-area-chart.stories.tsx
- packages/visualizations/package.json
- packages/visualizations/src/Area.tsx
Fixing the issue of wanting white lines between stacked area segments, but still having the segments visible if there is missing data on either side. 
https://contiamo.atlassian.net/browse/EX-105
> Ex 105 fix area stroke

- packages/visualizations-stories/src/vizualisations/1-bar-chart.stories.tsx
- packages/visualizations-stories/src/vizualisations/4-mixed-chart.stories.tsx
- packages/visualizations/src/AxisRules.tsx
- packages/visualizations/src/index.ts
Add (optional) axis rules to charts.
https://contiamo.atlassian.net/browse/EX-112
> Add axis rules.

- packages/visualizations-stories/src/vizualisations/4-mixed-chart.stories.tsx
- packages/visualizations/src/Labels.tsx
- packages/visualizations/src/index.ts
Simple text labels for axial charts.
https://contiamo.atlassian.net/browse/EX-110
> Add basic measure value labels.

- .github/workflows/master.yml
Use GitHub actions to auto-publish master. The same code as in operational-ui.
Related https://github.com/contiamo/operational-visualizations/issues/89
> Use GitHub actions to auto-publish master

- .github/renovate.json
- .github/workflows/master.yml
- package.json
- yarn.lock
Use comitzen and commitlint for comits. Use lerna release for canary
Related: https://github.com/contiamo/operational-visualizations/issues/89
> build(All): Add comitzen, commitlint

- .travis.yml
- README.md
Thanks to Chromatic for providing the visual testing platform that help us catch unexpected changes on time.
They enabled open-source plan for this project 👍
> chore(Readme): Add thanks note for Chromatic

- packages/visualizations/src/Axis.tsx
Not a final thing, just an idea
> feat(Axis): Limit max number of labels on the axis
